###服务启动端口号
server:
  port: 9100
###定义服务名称
spring:
  application:
    name: app-itmayiedu-eureka
###服务注册到eureka地址
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8100/eureka/
    ###因为该应用为注册中心，不会注册自己
    register-with-eureka: true
    ###是否需要从eureka上获取注册信息
    fetch-registry: true




